// Generated by CoffeeScript 1.6.3
(function() {
  var Rooms,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Rooms = (function(_super) {
    __extends(Rooms, _super);

    function Rooms(id, data) {
      this.id = id;
      if (data == null) {
        data = {};
      }
      Rooms.__super__.constructor.apply(this, arguments);
      this.set_data_fields("name", "homes", "timeline");
      this.set_data(data);
    }

    return Rooms;

  })(_SharedDoc);

}).call(this);
